spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:oauth2_db
    username: root
    password: toor
    initialization-mode: embedded
    platform: h2
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: <signing-key>